name: CI
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clone OpenCV
        run: |
          | git clone https://github.com/opencv/opencv
          | git clone https://github.com/opencv/opencv_contrib
          
      - name: Install Cuda Toolkit
        uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '12.1.0'
      
      - name: Configure
        run: |
          | cd opencv
          | mkdir build
          | cd build
          | cmake -D CMAKE_BUILD_TYPE=RELEASE -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=OFF -D OPENCV_ENABLE_NONFREE=ON -D WITH_CUDA=ON -D WITH_CUDNN=ON -D OPENCV_DNN_CUDA=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D CUDA_ARCH_BIN=7.5 -D WITH_CUBLAS=1 -D OPENCV_EXTRA_MODULES_PATH=..\..\opencv_contrib\modules -D HAVE_opencv_python3=ON -D BUILD_EXAMPLES=ON ..
        
      - name: Build
        run: |
          | cmake --build .
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: opencv/build

